import Head from "next/head";

const HeadMeta = ({title = 'Home'}) => {
    return (
        <>
            <Head>
                <title>{title} | Next.JS</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
        </>
    );
};
export default HeadMeta;